name: Run Automation Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Set up Gradle
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      # Run tests using Gradle (with the specified command)
      - name: Run Gradle tests
        working-directory: automatizacion-web  # Asegúrate de apuntar al directorio correcto de tu proyecto
        run: |
          chmod +x gradlew
          ./gradlew clean test aggregate

      # Optional: Upload Serenity reports as artifacts (if you want to save the reports)
      - name: Upload Serenity Reports
        uses: actions/upload-artifact@v3
        with:
          name: serenity-report
          path: automatizacion-web/target/site/serenity/  # Ajusta la ruta si es diferente
