name: Run Automation Tests

on:
  push:
    branches:
      - master  # Se ejecutará cuando hagas push a master
  pull_request:
    branches:
      - master  # Se ejecutará en los PR hacia master
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Paso para hacer checkout del código
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      # Paso para configurar Java
      - name: ☕ Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Paso para configurar Gradle
      - name: 📦 Set up Gradle
        uses: gradle/gradle-build-action@v2

      # Paso para ejecutar las pruebas de automatización
      - name: 🚀 Run tests
        working-directory: automatizacion-web  # 🔥 IMPORTANTE: Apuntar a la carpeta correcta
        run: |
          chmod +x gradlew
          ./gradlew clean test aggregate

      # Verificación de que el reporte de Serenity fue generado correctamente
      - name: 📂 Check if Serenity report exists
        run: ls automatizacion-web/target/site/serenity/

      # Paso para cargar el reporte de Serenity como artefacto
      - name: 📊 Upload Serenity Reports
        uses: actions/upload-artifact@v3
        with:
          name: serenity-report
          path: automatizacion-web/target/site/serenity/
