name: Run Automation Tests

on:
  push:
    branches:
      - master  # Se ejecutará cuando hagas push a master
  pull_request:
    branches:
      - master  # Se ejecutará en los PR hacia master
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub

jobs:
  test:
    runs-on: ubuntu-latest  # El runner de GitHub se ejecutará en Ubuntu

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: 📥 Checkout repository
        uses: actions/checkout@v3  # Descargar el código del repositorio

      # Paso 2: Configurar Java
      - name: ☕ Set up Java
        uses: actions/setup-java@v3  # Configurar Java 11
        with:
          distribution: 'temurin'
          java-version: '11'

      # Paso 3: Configurar Gradle
      - name: 📦 Set up Gradle
        uses: gradle/gradle-build-action@v2  # Configurar Gradle

      # Paso 4: Ejecutar las pruebas de automatización
      - name: 🚀 Run tests
        working-directory: automatizacion-web  # Apuntar al directorio correcto donde está la automatización
        run: |
          chmod +x gradlew  # Asegurarse de que el script gradlew sea ejecutable
          ./gradlew clean test aggregate  # Ejecutar las pruebas y generar los reportes de Serenity

      # Paso 5: Verificar si los reportes de Serenity se generaron correctamente
      - name: 📂 Check if Serenity report exists
        run: ls automatizacion-web/target/site/serenity/  # Verificar que los reportes existen

      # Paso 6: Subir el reporte de Serenity como artefacto (usando la versión v1 de upload-artifact)
      - name: 📊 Upload Serenity Reports
        uses: actions/upload-artifact@v1  # Usar la versión v1 de upload-artifact
        with:
          name: serenity-report
          path: automatizacion-web/target/site/serenity/

      # Si quieres hacer una prueba para ver si el error persiste:
      # Paso 7: (Alternativa) Si el paso anterior sigue fallando, comprimir el reporte y subirlo manualmente
      - name: 📂 Zip Serenity report
        run: |
          zip -r serenity-report.zip automatizacion-web/target/site/serenity/

      - name: 📊 Upload Serenity Reports manually
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/zip" \
            --data-binary @serenity-report.zip \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/assets?name=serenity-report.zip"
