name: Run Serenity Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant execute permissions to Gradle Wrapper
        run: chmod +x automatizacion-web/gradlew

      - name: Run Tests with Gradle
        run: ./gradlew clean test aggregate
        working-directory: automatizacion-web

      - name: Upload Serenity Reports
        uses: actions/upload-artifact@v4  # Cambio a v4
        with:
          name: serenity-report
          path: automatizacion-web/target/site/serenity/
          retention-days: 30  # Se mantiene el artefacto por 30 días
